version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TwojeMocneHaslo123!
    ports:
      - "1433:1433"

  app:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=CarRentalDb;User Id=sa;Password=TwojeMocneHaslo123!;TrustServerCertificate=True